# Disable ALL JPA/DataSource auto-configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration

# Force Datastore
persistence.unit=datastore
app.localdatastore.port=8484
app.enable.devserver.login=true
app.frontend.url=http://localhost:4200
app.taskqueue.active=true

# Explicitly disable data source
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=